name: user_repository
description: Dart package which manages the user domain.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  equatable: ^2.0.0
  odoo_rpc:
    git:
      url: https://github.com/joeybuddy/odoo-rpc-dart.git
  logger: ^1.0.0
  odoo_repository:
    path: ../../.
